version: '3.1'
services:
  web_server:
    env_file: .env.prod
    image: klotzandrew/rorschach_web_server
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: mix phoenix.server
    environment:
      MARKET_URL: ${MARKET_URL}
      MARKET_STREAM_URL: ${MARKET_STREAM_URL}

  db:
    image: postgres

  web_client:
    image: klotzandrew/rorschach_web_client
    ports:
      - "80:80"
