version: '2'
services:
  market_client:
    build: ./market_client
    ports:
      - "5000:5000"
    volumes:
      - ./market_client:/code
    command: bash atfeed-httpserver/bin/init.sh
    environment:
      CLIENT_PORT: 5000
      SERVER_HOST: activetick1.activetick.com
      API_KEY: ${API_KEY}
      AT_USER_ID: ${AT_USER_ID}
      AT_PASSWORD: ${AT_PASSWORD}

