version: '2'
services:
  market_client:
    build: ./market_client
    ports:
      - "5000:5000"
    volumes:
      - ./market_client:/code
    command: bash atfeed-httpserver/bin/init.sh
    environment:
      CLIENT_PORT: 5000
      SERVER_HOST: activetick1.activetick.com
      API_KEY: ${API_KEY}
      AT_USER_ID: ${AT_USER_ID}
      AT_PASSWORD: ${AT_PASSWORD}

  web_server:
    build: ./web_server
    ports:
      - "4000:4000"
    volumes:
      - ./web_server:/code
    depends_on:
      - db
      - market_client_demo
    command: mix phoenix.server

  db:
    image: postgres

  market_client_demo:
    build: ./market_client_demo
    volumes:
      - ./market_client_demo:/code
    command: node app.js
    ports:
      - "5020:5020"
